### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by mcolladoio** [Clivern/Walrus#107]
**Is your feature request related to a problem? Please describe.**
A Windows binary is not available con Releases

**Describe the solution you'd like**
Create a binary release for the agent service for Windows.

**Comment by Clivern** [comment]
Hi @mcolladoio, 

I added the windows binaries https://github.com/Clivern/Walrus/releases/tag/v0.1.7. actually I never tested walrus with windows but i think tower should be fine on windows and for the agent please make sure there is `tar` command, `mysqldump` for MySQL backups and `pg_dump` for postgresql database.

**Comment by mcolladoio** [comment]
Thanks! I'll try on the next week with a new project.
